name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
    - name: Install dependencies
      run: dotnet restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal BulletSharp/BulletSharp.DotNetCore.csproj
